title:             浙大土壤博士生论坛
email:             12014067@zju.edu.cn 
description:       2022年浙江大学“土壤健康与农业可持续发展”博士生论坛"
author:            Xinwei Song
url:               "https://SoilPhDForum.github.io/project.html"

# Social Profiles
github_username:   SoilPhDForum

# Build settings
markdown:          kramdown
paginate:          3
plugins:
  - jekyll-feed
  - jekyll-paginate
